#!/bin/sh

# This shell script downloads a recent copy of KaTeX and installs it into
# the redemine_plugin_katex redmine plugin.

# latest as of 2023/11/16
katexVersion=0.16.9

katexURL=https://github.com/KaTeX/KaTeX/releases/download/v$katexVersion/katex.tar.gz

mkdir -p assets/images
mkdir -p assets/javascripts
mkdir -p assets/stylesheets

mkdir katexTmp
cd katexTmp

# Get the KaTeX package
wget -O katex.tar.gz $katexURL
tar xvf katex.tar.gz --strip-components=1

# Copy the required javascript
cp katex.min.js ../assets/javascripts
cp contrib/auto-render.min.js ../assets/javascripts

# Copy the required fonts
cp -R fonts ../assets/javascripts

# Copy the required CSS
cp katex.min.css ../assets/stylesheets

# Now cleanup!
cd ..
rm -rf katexTmp
